type: evidential_topk
map_uncertainty: true
backbone: lss
dataset: carla
train_set: train
val_set: val
logdir: outputs/carla/lss_evidential_topk2_vehicle_e8
batch_size: 32
learning_rate: 0.01
weight_decay: 0.0000001
num_epochs: 40
loss: ce
ood: true
pos_class: 'vehicle'
n_classes: 2
classes: ['vehicle', 'background']
weights: [2.0, 1.0]
top_k: 800
map_label_expand_size: 8
