type: evidential_topk
map_uncertainty: true
backbone: cvt
dataset: nuscenes
train_set: train_comb
val_set: val_comb
logdir: outputs/nuscenes/cvt_evidential_topk2_vehicle
batch_size: 8
learning_rate: 0.05
weight_decay: 0.0000001
num_epochs: 40
loss: ce
ood: true
pos_class: 'vehicle'
n_classes: 2
classes: ['vehicle', 'background']
weights: [2.0, 1.0]
top_k: 50
map_label_expand_size: 4
pretrained: outputs/nuscenes/cvt_baseline_vehicle/19.pt
