type: evidential_topk
map_uncertainty: true
backbone: pointbev
dataset: nuscenes
train_set: train_comb
val_set: val_comb
logdir: outputs/nuscenes/pointbev_evidential_topk2_vehicle_d1
batch_size: 8
learning_rate: 0.05
weight_decay: 0.0000001
num_epochs: 40
loss: ce
ood: true
pos_class: 'vehicle'
n_classes: 2
classes: ['vehicle', 'background']
weights: [2.0, 1.0]
top_k: 200
map_label_expand_size: 0
# pretrained: outputs/nuscenes/pointbev_evidential_topk2_vehicle/10.pt
