type: baseline
backbone: lss
dataset: nuscenes
train_set: train_comb
val_set: val_comb
logdir: outputs/nuscenes/lss_baseline_bicycle_motorcycle
batch_size: 16
learning_rate: 0.001
weight_decay: 0.0000001
num_epochs: 40
loss: ce
ood: false
pos_class: 'debug_bicycle_motorcycle'
n_classes: 2
classes: ['bicycle_motorcycle', 'background']
weights: [100.0, 1.0]
