type: baseline
backbone: lss
dataset: nuscenes
train_set: train
val_set: val
logdir: outputs/nuscenes/lss_baseline_vehicle
batch_size: 32
learning_rate: 0.001
weight_decay: 0.0000001
num_epochs: 20
loss: ce
ood: false
pos_class: 'vehicle'
n_classes: 2
classes: ['vehicle', 'background']
weights: [2.0, 1.0]
