type: evidential
backbone: lss
dataset: nuscenes
train_set: train_comb
val_set: val_comb
logdir: outputs/nuscenes/lss_evidential_vehicle_debug
batch_size: 16
learning_rate: 0.001
weight_decay: 0.0000001
num_epochs: 20
loss: ce
ood: true
pos_class: 'vehicle'
n_classes: 2
classes: ['vehicle', 'background']
weights: [2.0, 1.0]
